from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(236, 368)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TextWindow = QtWidgets.QLabel(self.centralwidget)
        self.TextWindow.setGeometry(QtCore.QRect(0, 0, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.TextWindow.setFont(font)
        self.TextWindow.setStyleSheet("QLabel{\n"
                                        "qproperty-alignment:\'AlignVCenter |AlignRight\';\n"
                                        "border:1px solid gray;\n"
                                        "}\n"
                                        "background-color:white;")
        self.TextWindow.setObjectName("TextWindow")
        self.Seven = QtWidgets.QPushButton(self.centralwidget)
        self.Seven.setGeometry(QtCore.QRect(-2, 129, 61, 61))
        self.Seven.setObjectName("Seven")
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(57, 129, 61, 61))
        self.eight.setObjectName("eight")
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(116, 129, 61, 61))
        self.nine.setObjectName("nine")
        self.mult = QtWidgets.QPushButton(self.centralwidget)
        self.mult.setGeometry(QtCore.QRect(175, 129, 61, 61))
        self.mult.setObjectName("mult")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(57, 188, 61, 61))
        self.five.setObjectName("five")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(175, 188, 61, 61))
        self.minus.setObjectName("minus")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(-2, 188, 61, 61))
        self.four.setObjectName("four")
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(116, 188, 61, 61))
        self.six.setObjectName("six")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(57, 247, 61, 61))
        self.two.setObjectName("two")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(175, 247, 61, 61))
        self.plus.setObjectName("plus")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(-2, 247, 61, 61))
        self.one.setObjectName("one")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(116, 247, 61, 61))
        self.three.setObjectName("three")
        self.equ = QtWidgets.QPushButton(self.centralwidget)
        self.equ.setGeometry(QtCore.QRect(176, 306, 61, 61))
        self.equ.setObjectName("equ")
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(-2, 306, 121, 61))
        self.zero.setObjectName("zero")
        self.point = QtWidgets.QPushButton(self.centralwidget)
        self.point.setGeometry(QtCore.QRect(117, 306, 61, 61))
        self.point.setObjectName("point")
        self.percent = QtWidgets.QPushButton(self.centralwidget)
        self.percent.setGeometry(QtCore.QRect(116, 70, 61, 61))
        self.percent.setObjectName("percent")
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(175, 70, 61, 61))
        self.divide.setObjectName("divide")
        self.AllCrear = QtWidgets.QPushButton(self.centralwidget)
        self.AllCrear.setGeometry(QtCore.QRect(-2, 70, 61, 61))
        self.AllCrear.setObjectName("AllCrear")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(57, 70, 61, 61))
        self.clear.setObjectName("clear")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TextWindow.setText(_translate("MainWindow", "0"))
        self.Seven.setText(_translate("MainWindow", "7"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.mult.setText(_translate("MainWindow", "*"))
        self.five.setText(_translate("MainWindow", "5"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.four.setText(_translate("MainWindow", "4"))
        self.six.setText(_translate("MainWindow", "6"))
        self.two.setText(_translate("MainWindow", "2"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.one.setText(_translate("MainWindow", "1"))
        self.three.setText(_translate("MainWindow", "3"))
        self.equ.setText(_translate("MainWindow", "="))
        self.zero.setText(_translate("MainWindow", "0"))
        self.point.setText(_translate("MainWindow", "."))
        self.percent.setText(_translate("MainWindow", "%"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.AllCrear.setText(_translate("MainWindow", "AC"))
        self.clear.setText(_translate("MainWindow", "C"))



